export const ADD_CATEGORY = 'ADD_CATEGORY';
export const STORE_NEW_CATEGORY_NAME = 'STORE_NEW_CATEGORY_NAME';
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const TOGGLE_ITEM = "TOGGLE_ITEM";