export const ADD_CATEGORY = 'ADD_CATEGORY';
export const STORE_NEW_CATEGORY_NAME = 'STORE_NEW_CATEGORY_NAME';
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const TOGGLE_ITEM = "TOGGLE_ITEM";
export const START_ADDING_CATEGORY = "START_ADDING_CATEGORY";
export const CANCEL_ADDING_CATEGORY = "CANCEL_ADDING_CATEGORY";

export const START_ADDING_ITEM = "START_ADDING_ITEM";
export const CANCEL_ADDING_ITEM = "CANCEL_ADDING_ITEM";

export const STORE_NEW_ITEM_NAME = "STORE_NEW_ITEM_NAME";

export const START_EDITING_CATEGORY = "START_EDITING_CATEGORY";

export const CANCEL_EDITING_CATEGORY = "CANCEL_EDITING_CATEGORY";

export const STORE_CATEGORY_NAME = "STORE_CATEGORY_NAME";

export const SAVE_CATEGORY_NAME = "SAVE_CATEGORY_NAME";

export const REMOVE_ITEM = "REMOVE_ITEM";

export const ADD_ITEM = "ADD_ITEM";

export const CANCEL_EDITING_ITEM = "CANCEL_EDITING_ITEM"

export const STORE_ITEM_NAME = "STORE_ITEM_NAME"

export const SAVE_ITEM_NAME = "SAVE_ITEM_NAME";

export const START_EDITING_ITEM = "START_EDITING_ITEM"